version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Building application...
      - ./gradlew --stacktrace clean build
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest_develop -f docker/dev.Dockerfile .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest_develop
reports:
  JacocoReport:
    files:
      - '**/*'
    base-directory: build/test-results/test
cache:
  paths:
    - '/root/.gradle/wrapper/**/*'
